In [84]:
# @title Data manipulation with Python
import pandas as pd

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

In [85]:
# @title menampilkan dataset
print(df.shape)
df.head()
display (df.head())

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [86]:
# @title melihat missing value
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [87]:
# @title Menghapus Kolom yang tidak relevan untuk pelatihan model
kolom_sampah = ['PassengerId', 'Name', 'Ticket', 'Cabin']
df_bersih = df.drop(columns=kolom_sampah)

In [88]:
# @title Menangani missing value pada kolom age
median_umur = df_bersih['Age'].median()
df_bersih['Age'] = df_bersih['Age'].fillna(median_umur)

In [89]:
# @title Menghapus sisa baris yang masih memiliki missing values (misal ada 2 baris kosong di
# kolom 'Embarked')
df_bersih = df_bersih.dropna()

In [90]:
# @title Melihat kembali sum of missing value
# tulis lagi yak gimana lihatnya 🤭
df_bersih.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [91]:
# @title One hot encoding kalo kategoorikal
df_final = pd.get_dummies(df_bersih, columns=['Sex', 'Embarked'], drop_first=True, dtype='int')
df_final

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0
2,1,3,26.0,0,0,7.9250,0,0,1
3,1,1,35.0,1,0,53.1000,0,0,1
4,0,3,35.0,0,0,8.0500,1,0,1
...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,1,0,1
887,1,1,19.0,0,0,30.0000,0,0,1
888,0,3,28.0,1,2,23.4500,0,0,1
889,1,1,26.0,0,0,30.0000,1,0,0
890,0,3,32.0,0,0,7.7500,1,1,0

In [92]:
# @title normalisasi menggunakan min max scaler
from sklearn.preprocessing import MinMaxScaler
scaler_minmax = MinMaxScaler()
kolom_semua = df_final.columns
df_final[kolom_semua] = scaler_minmax.fit_transform(df_final)

In [93]:
# @title tampilkan kembali hasil data final
display(df_final.head())

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0.0,1.0,0.271174,0.125,0.0,0.014151,1.0,0.0,1.0
1,1.0,0.0,0.472229,0.125,0.0,0.139136,0.0,0.0,0.0
2,1.0,1.0,0.321438,0.000,0.0,0.015469,0.0,0.0,1.0
3,1.0,0.0,0.434531,0.125,0.0,0.103644,0.0,0.0,1.0
4,0.0,1.0,0.434531,0.000,0.0,0.015713,1.0,0.0,1.0